name: ci
 
on:
 push:
   branches: main
 
jobs:
 main:
   runs-on: ubuntu-latest
   steps:
     -  name: Check out the repo
        uses: actions/checkout@v2
     -
       name: Setup Docker Buildx
       uses: docker/setup-buildx-action@v1
     -
       name: Set up QEMU
       uses: docker/setup-qemu-action@v1
     -
       name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     -
       name: Build and push
       uses: docker/build-push-action@v2
       with:
         context: .
         file: Dockerfile
         platforms: linux/amd64,linux/arm64
         push: true
         tags: |
           tag1consulting/modphp74-ubi8-base:latest

     - name: Push To quay.io
          id: push-to-quay
          uses: redhat-actions/push-to-registry@v2
          with:
            image: modphp74-ubi8-base
            tags: latest ${{ github.ref }}
            registry: quay.io/tag1consulting
            username: tag1consulting+github
            password: ${{ secrets.QUAY_REGISTRY_PASSWORD }}
