name: image-update

on:
  schedule:
    - cron: "0 10 * * *"

jobs:
 update:
   runs-on: ubuntu-latest
   steps:
     -  name: Check out the repo
        uses: actions/checkout@v2
     -
       name: Check if update available
       id: check
       uses: twiddler/is-my-docker-parent-image-out-of-date@v1
       with:
         base-image: registry.access.redhat.com/ubi8/php-74:latest
         image: quay.io/tag1consulting/modphp74-ubi8-base:latest
     -
       name: Setup Docker Buildx
       uses: docker/setup-buildx-action@v1
     -
       name: Set up QEMU
       uses: docker/setup-qemu-action@v1
     -
       name: Login to Quay.io
       uses: docker/login-action@v1
       with:
         registry: quay.io
         username: tag1consulting+github
         password: ${{ secrets.QUAY_REGISTRY_PASSWORD }}

     -
       name: Docker meta
       id: meta
       uses: docker/metadata-action@v3
       with:
         images: quay.io/tag1consulting/modphp74-ubi8-base
     - name: Get current date
       id: date
       run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
     -
       name: Build and push
       uses: docker/build-push-action@v2
       with:
         context: .
         file: Dockerfile
         platforms: linux/amd64,linux/arm64
         push: true
         tags: ${{ steps.meta.outputs.tags }}, ${{ steps.date.outputs.date }}
         labels: ${{ steps.meta.outputs.labels }}, ${{ steps.date.outputs.date }}

       if: steps.check.outputs.out-of-date == 'true'

